on:
  schedule:
    - cron: '0 */24 * * *'
  push:
    branches:
      - master
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.GIT_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name Arpit Bhalla
        git config user.email 68342121+arpit-bhalla@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push
        fi
